sudo: required

services:
  - docker

before_install:
  - sudo mkdir -p /etc/docker/certs.d/registry-cn.datapipeline.com:10111
  - sudo openssl aes-256-cbc -d -K $OPENSSL_KEY -iv $OPENSSL_IV -in docker-registry.crt.enc -out /etc/docker/certs.d/registry-cn.datapipeline.com:10111/ca.crt

install:
  - make build
  - docker tag dp-docker-stats registry-cn.datapipeline.com:10111/dp-docker-stats:travis-rc2
  - docker push registry-cn.datapipeline.com:10111/dp-docker-stats:travis
  - docker rmi registry-cn.datapipeline.com:10111/dp-docker-stats:travis

script:
  - make clean